"""
Content_Generator.py - MUSE Tool
Generates marketing content, whitepapers, and mock data.
"""
import sys
import os
from pathlib import Path
from datetime import datetime

OUTPUT_DIR = Path(__file__).parent.parent / "Content_Forge"

TEMPLATES = {
    "whitepaper": """# {subject}
## Executive Summary
This whitepaper explores the innovative approaches to {subject}.

## Introduction
In today's rapidly evolving landscape, {subject} represents a critical area of development.

## Key Concepts
### Core Principles
- Innovation-first approach
- User-centric design
- Security by default
- Scalable architecture

### Technical Foundation
The foundation of {subject} rests on proven technologies combined with novel approaches.

## Implementation Strategy
1. Phase 1: Foundation (Weeks 1-4)
2. Phase 2: Core Development (Weeks 5-12)
3. Phase 3: Integration (Weeks 13-16)
4. Phase 4: Launch (Weeks 17-20)

## Conclusion
{subject} positions stakeholders at the forefront of technological advancement.

---
*Generated by HeadyMuse on {date}*
""",
    "marketing": """# {subject} - Marketing Brief

## Value Proposition
Transform your workflow with {subject}.

## Key Benefits
- **Efficiency**: Reduce time spent on manual tasks by 60%
- **Reliability**: 99.9% uptime guarantee
- **Security**: Enterprise-grade protection
- **Scalability**: Grows with your needs

## Target Audience
- Technical teams seeking automation
- Organizations prioritizing security
- Growth-focused enterprises

## Messaging Pillars
1. Innovation without complexity
2. Security without compromise
3. Scale without limits

## Call to Action
Start your journey with {subject} today.

---
*Generated by HeadyMuse on {date}*
""",
    "data": """# Mock Data: {subject}

## Sample Records
| ID | Name | Status | Created |
|----|------|--------|---------|
| 001 | Alpha | Active | 2024-01-15 |
| 002 | Beta | Pending | 2024-01-16 |
| 003 | Gamma | Active | 2024-01-17 |
| 004 | Delta | Inactive | 2024-01-18 |
| 005 | Epsilon | Active | 2024-01-19 |

## Statistics
- Total Records: 5
- Active: 3
- Pending: 1
- Inactive: 1

## Schema
```json
{{
  "id": "string",
  "name": "string",
  "status": "enum[Active, Pending, Inactive]",
  "created": "datetime"
}}
```

---
*Generated by HeadyMuse on {date}*
"""
}

def generate_content(mode, subject):
    """Generate content based on mode and subject."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    template = TEMPLATES.get(mode, TEMPLATES["marketing"])
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    content = template.format(subject=subject, date=date_str)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_subject = "".join(c if c.isalnum() else "_" for c in subject)[:30]
    output_file = OUTPUT_DIR / f"{mode}_{safe_subject}_{timestamp}.md"
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"[MUSE] Generated {mode} content for '{subject}'")
    print(f"  Output: {output_file}")
    return str(output_file)

if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "marketing"
    subject = sys.argv[2] if len(sys.argv) > 2 else "HeadySystems"
    generate_content(mode, subject)
