"""
Hydrator.py - BUILDER Tool
Scaffolds new project structures.
"""
import sys
import os
from pathlib import Path
from datetime import datetime

TEMPLATES = {
    "python": {
        "dirs": ["src", "tests", "docs"],
        "files": {
            "src/__init__.py": "",
            "tests/__init__.py": "",
            "README.md": "# {project_name}\n\nGenerated by HeadyBuilder on {date}",
            "requirements.txt": "# Dependencies\n",
            ".gitignore": "__pycache__/\n*.pyc\n.env\nvenv/\n"
        }
    },
    "web": {
        "dirs": ["src", "public", "tests"],
        "files": {
            "src/index.js": "// Entry point\nconsole.log('Hello from {project_name}');",
            "public/index.html": "<!DOCTYPE html>\n<html><head><title>{project_name}</title></head><body></body></html>",
            "README.md": "# {project_name}\n\nGenerated by HeadyBuilder on {date}",
            "package.json": '{{"name": "{project_name}", "version": "1.0.0"}}'
        }
    },
    "default": {
        "dirs": ["src", "docs", "tests"],
        "files": {
            "README.md": "# {project_name}\n\nGenerated by HeadyBuilder on {date}",
            ".gitignore": "*.log\n.env\n"
        }
    }
}

def hydrate_project(project_name, template="default"):
    """Create a new project structure."""
    base_dir = Path(__file__).parent.parent / "Playground" / "Projects"
    project_dir = base_dir / project_name
    
    if project_dir.exists():
        print(f"Project {project_name} already exists at {project_dir}")
        return str(project_dir)
    
    template_config = TEMPLATES.get(template, TEMPLATES["default"])
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    project_dir.mkdir(parents=True, exist_ok=True)
    
    for subdir in template_config["dirs"]:
        (project_dir / subdir).mkdir(parents=True, exist_ok=True)
    
    for file_path, content in template_config["files"].items():
        full_path = project_dir / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        formatted_content = content.format(project_name=project_name, date=date_str)
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(formatted_content)
    
    print(f"Project '{project_name}' hydrated at {project_dir}")
    print(f"  Directories: {', '.join(template_config['dirs'])}")
    print(f"  Files: {len(template_config['files'])} created")
    return str(project_dir)

if __name__ == "__main__":
    project = sys.argv[1] if len(sys.argv) > 1 else "NewProject"
    template = sys.argv[2] if len(sys.argv) > 2 else "default"
    hydrate_project(project, template)
